import { BiLogoTypescript } from "react-icons/bi";
import { FaJava, FaNode } from "react-icons/fa";
import { FaHtml5 } from "react-icons/fa6";
import { RiNextjsFill } from "react-icons/ri";
import {
  SiDocker,
  SiGit,
  SiHibernate,
  SiPostgresql,
  SiReact,
  SiJavascript,
  SiSpringboot,
  SiSwagger,
  SiTypescript,
  SiNestjs,
} from "react-icons/si";

export const skills = [
  {
    name: "Java",
    category: "backend",
    level: 50,
    experience: "1 ano",
    projects: 2,
    icon: FaJava,
  },
  {
    name: "Spring Boot",
    category: "backend",
    level: 50,
    experience: "1 ano",
    projects: 2,
    icon: SiSpringboot,
  },
  {
    name: "Hibernate",
    category: "backend",
    level: 35,
    experience: "1 ano",
    projects: 2,
    icon: SiHibernate,
  },
  {
    name: "REST API",
    category: "backend",
    level: 65,
    experience: "2 anos",
    projects: 4,
    icon: SiSwagger,
  },
  {
    name: "Node.js",
    category: "backend",
    level: 55,
    experience: "2 anos",
    projects: 4,
    icon: FaNode,
  },
  {
    name: "TypeScript",
    category: "backend",
    level: 55,
    experience: "2 anos",
    projects: 4,
    icon: BiLogoTypescript,
  },
  {
    name: "Nest.JS",
    category: "backend",
    level: 55,
    experience: "2 anos",
    projects: 3,
    icon: SiNestjs,
  },
  {
    name: "PostgreSQL",
    category: "database",
    level: 60,
    experience: "2 anos",
    projects: 4,
    icon: SiPostgresql,
  },
  {
    name: "Docker",
    category: "devops",
    level: 45,
    experience: "1 ano",
    projects: 4,
    icon: SiDocker,
  },
  {
    name: "Git",
    category: "devops",
    level: 60,
    experience: "2 anos",
    projects: 10,
    icon: SiGit,
  },
  {
    name: "Next.js",
    category: "frontend",
    level: 55,
    experience: "2 anos",
    projects: 4,
    icon: RiNextjsFill,
  },
  {
    name: "html",
    category: "frontend",
    level: 45,
    experience: "2 anos",
    projects: 3,
    icon: FaHtml5,
  },
  {
    name: "JavaScript",
    category: "frontend",
    level: 55,
    experience: "2 anos",
    projects: 4,
    icon: SiJavascript,
  },
  {
    name: "React",
    category: "frontend",
    level: 55,
    experience: "2 anos",
    projects: 5,
    icon: SiReact,
  },
];
